apiVersion: v2
version: 0.1.0  # Chart version
appVersion: "2.0.3"  # Penpot version
type: application
name: penpot
description: Helm chart for Penpot, the Open Source design and prototyping platform.
maintainers:
- name: Kaleidos INC
  url: https://kaleidos.net
home: https://penpot.app
icon: https://avatars.githubusercontent.com/u/30179644?s=200&v=4
sources:
- https://github.com/penpot/penpot/tree/main
- https://github.com/penpot/penpot-helm/tree/main
keywords:
- kubernetes
- penpot
- penpotapp
- design
- designsystem
- opensource
- ux
- ui
dependencies:
- name: postgresql
  version: 15.x.x  # appVersion >= 16.2.0
  repository: https://charts.bitnami.com/bitnami
  condition: global.postgresqlEnabled
- name: redis
  version: 19.x.x  # appVersion >= 7.2.4
  repository: https://charts.bitnami.com/bitnami
  condition: global.redisEnabled
